name: Update Question in Database

on:
  push:
    branches: [main]
    paths:
      - 'problems/**'
  workflow_dispatch:

jobs:
  update-question:
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm

      # Install all dependencies for all workspaces
      - name: Install all workspace dependencies
        run: npm ci

      # Build all workspace packages (important for local imports like @codequest/common)
      - name: Build all workspace packages
        run: npm run build --workspaces --if-present

      # Generate Prisma client (after build, in case types are needed)
      - name: Generate Prisma client
        run: cd packages/db && npx prisma generate --schema=prisma/schema.prisma

      # Update each problem in database
      - name: Update each problem in database
        run: |
          for problem in problems/*; do
            if [ -d "$problem" ]; then
              problem_slug=$(basename "$problem")
              echo "Updating $problem_slug"
              PROBLEM_SLUG=$problem_slug MOUNT_PATH=problems npx ts-node packages/db/prisma/updateQuestion.ts
            fi
          done
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
